export const SET_DARK_MODE = "SET_DARK_MODE";
export const TOGGLE_MODAL = "TOGGLE_MODAL";

// news
export const GET_FEATURED_NEWS = "GET_FEATURED_NEWS";
export const GET_TRENDING_NEWS = "GET_TRENDING_NEWS";

export const GET_NEWS_BY_ID = "GET_NEWS_BY_ID";

// matches
export const GET_UPCOMING_MATCHS = "GET_UPCOMING_MATCHS";

export const SORT_MODAL_TOGGLE = "SORT_MODAL_TOGGLE";

export const BG_COLOR_CHANGE = "BG_COLOR_CHANGE";

// userLogin set
export const LOGIN_TO_GET_A_TOKEN = "LOGIN_TO_GET_A_TOKEN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERROR = "LOGIN_ERROR";

// product
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

// home and navgationList
export const GET_HOME_PAGE_DETAILS = "GET_HOME_PAGE_DETAILS";
export const GET_HOME_PAGE_DETAILS_LOADING = "GET_HOME_PAGE_DETAILS_LOADING";
export const GET_HOME_PAGE_DETAILS_ERROR = "GET_HOME_PAGE_DETAILS_ERROR";

//filter value get
export const GET_FILTER_VALUE = "GET_FILTER_VALUE";
export const GET_FILTER_VALUE_LOADING = "GET_FILTER_VALUE_LOADING";
export const GET_FILTER_VALUE_ERROR = "GET_FILTER_VALUE_ERROR";

export const SET_GENDER_CHECK_VALUE = "SET_GENDER_CHECK_VALUE";
export const SET_SUB_CATEGORY_VALUE = "SET_SUB_CATEGORY_VALUE";
export const SET_CATEGORY_VALUE = "SET_CATEGORY_VALUE";
export const SET_ITEM_GROUP_VALUE = "SET_ITEM_GROUP_VALUE";

//clear filter
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const SET_FILTER = "SET_FILTER";

// productpagination set laoding true
export const SET_LOADING_PAGINATION = "SET_LOADING_PAGINATION";
export const SET_PAGINATION_OFFSET = "SET_PAGINATION_OFFSET";
export const SET_PAGINATION_LIST_END = "SET_PAGINATION_LIST_END";

// cardItems
export const GET_CARD_ITEMS = "GET_CARD_ITEMS";
export const GET_CARD_ITEMS_LOADING = "GET_CARD_ITEMS_LOADING";
export const GET_CARD_ITEMS_ERROR = "GET_CARD_ITEMS_ERROR";

export const CARD_ITEM_INCREMENT = "CARD_ITEM_INCREMENT";
export const CARD_ITEM_DECREMENT = "CARD_ITEM_DECREMENT";
export const CARD_ITEM_INCREMENT_DECREMENT_SERVER_SIDE_LOADING =
  "CARD_ITEM_INCREMENT_DECREMENT_SERVER_SIDE_LOADING";
export const CARD_ITEM_INCREMENT_DECREMENT_SERVER_SIDE_ERROR_OR_DONE =
  "CARD_ITEM_INCREMENT_DECREMENT_SERVER_SIDE_ERROR_OR_DONE";

export const CARD_ITEM_VALUE_REMOVE = "CARD_ITEM_VALUE_REMOVE";
export const CARD_ITEM_VALUE_REMOVE_SERVER_SIDE_LOADING =
  "CARD_ITEM_VALUE_REMOVE_SERVER_SIDE_LOADING";
export const CARD_ITEM_VALUE_REMOVE_SERVER_SIDE_ERROR_OR_DONE =
  "CARD_ITEM_VALUE_REMOVE_SERVER_SIDE_ERROR_OR_DONE";

export const LOG_OUT = "LOG_OUT";
// export const ADD_CARD_ITEM = "ADD_CARD_ITEM";

// Like
export const GET_LIKE_ITEMS = "GET_LIKE_ITEMS";
export const GET_LIKE_ITEMS_LOADING = "GET_LIKE_ITEMS_LOADING";
export const GET_LIKE_ITEMS_ERROR = "GET_LIKE_ITEMS_ERROR";

export const LIKE_UNLIKE_SERVER_SIDE_LOADING =
  "LIKE_UNLIKE_SERVER_SIDE_LOADING";
export const LIKE_UNLIKE_SERVER_SIDE_ERROR_DONE =
  "LIKE_UNLIKE_SERVER_SIDE_ERROR_DONE";

export const LIKE_ITEM_VALUE_ADD = "LIKE_ITEM_VALUE_ADD";
export const UNLIKE_ITEM_VALUE_REMOVE = "UNLIKE_ITEM_VALUE_REMOVE";

export const PLACE_ORDER_ITEMS = "PLACE_ORDER_ITEMS";
export const PLACE_ORDER_ITEMS_LOADING = "PLACE_ORDER_ITEMS_LOADING";
export const PLACE_ORDER_ITEMS_ERROR = "PLACE_ORDER_ITEMS_ERROR";

export const EDIT_ORDER_ITEM_LOADING = "EDIT_ORDER_ITEM_LOADING";
export const EDIT_ORDER_ITEM_BY_ID = "EDIT_ORDER_ITEM_BY_ID";
export const EDIT_ORDER_ITEM_ERROR = "EDIT_ORDER_ITEM_ERROR";

export const LIST_ORDER_ITEM_LOADING = "LIST_ORDER_ITEM_LOADING";
export const LIST_ORDER_ITEM = "LIST_ORDER_ITEM";
export const LIST_ORDER_ITEM_ERROR = "LIST_ORDER_ITEM_ERROR";

// app update modal
export const CHECK_UPDATE = "CHECK_UPDATE";
export const SET_SEARCH = "SET_SEARCH";
export const TOGGLE_SEARCH_MODEL = "TOGGLE_SEARCH_MODEL";

export const GET_GROUP_SIZE_LIST = "GET_GROUP_SIZE_LIST";
export const GET_GROUP_SIZE_LOADING = "GET_GROUP_SIZE_LOADING";
export const GET_GROUP_SIZE_LIST_ERROR = "GET_GROUP_SIZE_LIST_ERROR";

export const SET_REMARK_MODEL = "SET_REMARK_MODEL";
export const REMARK_ITEM_STATE_CHANGE = "SET_REMARK_ITEM_STATE_CHANGE";

export const SET_GROUP_MODEL = "SET_GROUP_MODEL";
export const SET_GROUP_ID_STATE_CHANGE = "SET_GROUP_ID_STATE_CHANGE";

export const SET_SIZE_MODEL = "SET_SIZE_MODEL";
export const SET_SIZE_ID_STATE_CHANGE = "SET_SIZE_ID_STATE_CHANGE";

export const ORDER_PDF_PAGE_HTML = "ORDER_PDF_PAGE_HTML";
export const ORDER_PED_PAGE_HTML_LOADING = "ORDER_PED_PAGE_HTML_LOADING";
export const ORDER_PDF_PAGE_HTML_ERROR = "ORDER_PDF_PAGE_HTML_ERROR";

// stone
export const ONCHANGE_STONE_VALUE = "ONCHANGE_STONE_VALUE";

export const GET_CUSTOMER_ITEMS = "GET_CUSTOMER_ITEMS";
export const GET_CUSTOMER_ITEMS_ERROR = "GET_CUSTOMER_ITEMS_ERROR";
export const GET_CUSTOMER_ITEMS_LOADING = "GET_CUSTOMER_ITEMS_LOADING";

export const SET_LOADING_SPINNER_ACTION = "SET_LOADING_SPINNER_ACTION";

// get deleivrty:
export const GET_DELIVERY_ITEMS_LOADING = "GET_DELIVERY_ITEMS_LOADING";
export const GET_DELIVERY_ITEMS = "GET_DELIVERY_ITEMS";
export const GET_DELIVERY_ITEMS_ERROR = "GET_DELIVERY_ITEMS_ERROR";

// get deleivrty: report
export const GET_DELIVERY_REPORTS_LOADING = "GET_DELIVERY_REPORTS_LOADING";
export const GET_DELIVERY_REPORTS = "GET_DELIVERY_REPORTS";
export const GET_DELIVERY_REPORTS_ERROR = "GET_DELIVERY_REPORTS_ERROR";

// customerDelievryDetilasList : Date
export const CUSTOMER_DELIVERY_DETAILS_LOADING =
  "CUSTOMER_DELIVERY_DETAILS_LOADING";
export const CUSTOMER_DELIVERY_DETAILS_ERROR =
  "CUSTOMER_DELIVERY_DETAILS_ERROR";
export const CUSTOMER_DELIVERY_DETAILS_LIST = "CUSTOMER_DELIVERY_DETAILS_LIST";

export const DELIVERY_STATE_CAHNGE = "DELIVERY_STATE_CAHNGE";

export const CITY_DATA_SET = "CITY_DATA_SET";
export const LAND_DATA_SET = "LAND_DATA_SET";
export const ADMIN_SERVICE_DATA_SET = "ADMIN_SERVICE_DATA_SET";

export const PRODUCT_DATA_LOGOUT = "PRODUCT_DATA_LOGOUT";

// selection list
export const PENDING_LIST_SELECTION = "PENDING_LIST_SELECTION";

export const PENDING_ORDER_STATE_SELECTION_ADD =
  "PENDING_ORDER_STATE_SELECTION_ADD";

export const PENDING_ORDER_STATE_SELECTION_REMOVE =
  "PENDING_ORDER_STATE_SELECTION_REMOVE";

export const PENDING_ORDER_STATE_SELECTION_EMPTY =
  "PENDING_ORDER_STATE_SELECTION_EMPTY";

export const REMOVE_SELECTION_PENDING_LIST = "REMOVE_SELECTION_PENDING_LIST";

export const GET_BOOKING_ITEMS_ERROR = "GET_BOOKING_ITEMS_ERROR";
export const GET_BOOKING_ITEMS = "GET_BOOKING_ITEMS";
export const GET_BOOKING_ITEMS_LOADING = "GET_BOOKING_ITEMS_LOADING";

export const GET_PAYMENT_ITEMS_LOADING = "GET_PAYMENT_ITEMS_LOADING";
export const GET_PAYMENT_ITEMS = "GET_PAYMENT_ITEMS";
export const GET_PAYMENT_ITEMS_ERROR = "GET_PAYMENT_ITEMS_ERROR";

export const PAYMENT_MODAL_TOGGLE = "PAYMENT_MODAL_TOGGLE";

export const PAYMENT_ADD_METHOD_BOOKING_MODAL_TOGGLE =
  "PAYMENT_ADD_METHOD_BOOKING_MODAL_TOGGLE";

export const SELECTION_ALL_PENDING_SELECTION_LIST =
  "SELECTION_ALL_PENDING_SELECTION_LIST";

// one time booking report

export const GET_ONETIME_BOOKING_REPORT = "GET_ONETIME_BOOKING_REPORT";
export const GET_ONETIME_BOOKING_REPORT_ERROR =
  "GET_ONETIME_BOOKING_REPORT_ERROR";
export const GET_ONETIME_BOOKING_REPORT_LOADING =
  "GET_ONETIME_BOOKING_REPORT_LOADING";

// max debit date check
export const MAX_DEBIT_DATE = "MAX_DEBIT_DATE";

export const LIKE_UNLIKE_LOADING = "LIKE_UNLIKE_LOADING";
export const LIKE_UNLIKE_DONE = "LIKE_UNLIKE_DONE";
export const REMOVE_FROM_LIKE_LIST = "REMOVE_FROM_LIKE_LIST";

export const ADD_TO_WHISH_LIST_MODAL = "ADD_TO_WHISH_LIST_MODAL";

export const GET_FILTER_DATA = "GET_FILTER_DATA";
